#!/usr/bin/env python3

'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

import itertools

def fib():
    a, b = 1, 2
    while True:
        yield a
        a, b = b, a + b
    
def main():
    limit = 4e6
    lower = itertools.takewhile(lambda x: x<limit, fib())
    even = itertools.filterfalse(lambda x: x%2, lower)
    result = sum(even)
    print('Result: ', result)

if __name__ == '__main__':
    main()
